maps/de_rats.res
maps/de_rats.txt
sound/misc/a-yeah4.WAV
sound/misc/g-yeah3.wav
sound/misc/doh7.wav
sound/misc/gemein.wav
sound/misc/ahh.wav
sound/misc/g-bye1.wav
sound/misc/g-goodgame1.wav
sound/misc/g-affirmative.wav
sound/misc/g-greatshot1.wav
sound/misc/g-hi2.wav
sound/misc/g-lets_go.wav
sound/misc/g-medic3.wav
sound/misc/g-negative.wav
sound/misc/g-oops1.wav
sound/misc/g-sorry1.wav
sound/misc/g-thanks1.wav