//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/jail_aj_bananamuffin.html
halflife.wad
decals.wad
xeno.wad
cstrike.wad
cs_dust.wad
models/player/gsg9/gsg9.mdl
models/player/guerilla/guerilla.mdl
sound/baseleader.wav
sound/swedishhousemafia.wav
sound/whatislove.wav
sound/melodiesout.wav
maps/jail_aj_bananamuffin.bsp
