////////////////////////////////////////////////////////////////// Resources file, created with 17Ims, free software !!!//// © Chapo 2005 - Infos @ http://www.17buddies.net//// Can you play all of our maps?? Sure not!!//
halflife.wad
maps/soccerjam.bsp
maps/soccerjam.res
models/kickball/ball.mdl
sound/kickball/amaze.wav
sound/kickball/boomchakalaka.wav
sound/kickball/diebitch.wav
sound/kickball/gotball.wav
sound/kickball/laugh.wav
sound/kickball/perfect.wav
sound/kickball/pussy.wav
sound/kickball/bday.wav
sound/kickball/bounce.wav
sound/kickball/distress.wav
sound/kickball/kicked.wav
sound/kickball/levelup.wav
sound/kickball/prepare.wav
sound/kickball/returned.wav